### ISSUE TITLE
ping result not returned for some unreachable hosts

### ISSUE THREAD

**Issue by Rocking80** [kyan001/ping3#14]
```python
from ping3 import ping
res = ping('10.128.20.30')
print(res)
```

The code hang there for a very long time and never returns, even I set timeout and count to 2.
But when I try shell command `ping` it can return results:

```shell
[root@host~]# ping -c 2 10.128.20.30
PING 10.228.94.234 (10.128.20.30) 56(84) bytes of data.

--- 10.128.20.30 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 40ms

```

**Comment by kyan001** [comment]
Hi @Rocking80 

As I run some tests on my PC, I cannot reproduce that "long hang with no returns". If you can send the test code with your OS/version info that would be helpful. Also, you can try to run the same code with `ping3.DEBUG = True`, to see if there any useful output exists.

Since different platforms do different implementations of networks, and I cannot cover all of them. That's why your feedback is important to me. Thanks.

**Comment by dorty3541** [comment]
> Hi @Rocking80
> 
> As I run some tests on my PC, I cannot reproduce that "long hang with no returns". If you can send the test code with your OS/version info that would be helpful. Also, you can try to run the same code with `ping3.DEBUG = True`, to see if there any useful output exists.
> 
> Since different platforms do different implementations of networks, and I cannot cover all of them. That's why your feedback is important to me. Thanks.

Hi,kyan001
I have the same issue,e.g:
```
[root@host-192-168-23-115 mysqld]# python3
Python 3.7.1 (default, Dec 20 2018, 13:50:48)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ping3 import ping
>>> res=ping('192.168.79.221')
^F^Z
[1]+  已停止               python3
您在 /var/spool/mail/root 中有邮件
[root@host-192-168-23-115 mysqld]# ping -c 2 192.168.79.221
PING 192.168.79.221 (192.168.79.221) 56(84) bytes of data.

--- 192.168.79.221 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1000ms

[root@host-192-168-23-115 mysqld]#
```
OS:CentOS Linux release 7.2.1511 (Core)   3.10.0-327.el7.x86_64
Python:3.7.1

**Comment by GoopyAspirin** [comment]
Hi @Rocking80

I have the same issue

**Comment by kyan001** [comment]
Hi @GoopyAspirin @Rocking80 @dorty3541,

I tried again and cannot reproduce the bug. So I add some debug output in the code. Can you guys update the version to at least 2.4.2 and run your codes again?

Update ping3: `python3 -m pip install -U ping3`
Run your code under DEBUG mode:
```py
>>> import ping3
>>> ping3.DEBUG = True
>>> ping3.ping('10.128.20.30')  # or any of your HostUnreachable IP.
```
Doing this should be some output start with "[DEBUG]" to console stderr. Paste your outputs and let's see what happened when it lose respond.

Thanks.

**Comment by GoopyAspirin** [comment]
Hi @kyan001
Thank you very much for your attention.

I still get the same problem.

I completely deleted ping3 and installed the latest version (2.4.3).

The environment in which the problem occurs is centos7.
But on my macOS it still works fine.

When a timeout occurs, the function pauses for up to five minutes.


`Python 3.6.8 (default, Aug  7 2019, 17:28:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ping3
>>> ping3.DEBUG = True
>>> ping3.ping('52.79.186.81')
[DEBUG] <Logger ping3 (DEBUG)>
[DEBUG] Function Called: ping('52.79.186.81')
[DEBUG] Function Called: send_one_ping({'sock': <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1, laddr=('0.0.0.0', 1)>, 'dest_addr': '52.79.186.81', 'icmp_id': 64096, 'seq': 0, 'size': 56})
[DEBUG] Destination Address: '52.79.186.81'
[DEBUG] Destination Address: 52.79.186.81
[DEBUG] Sent ICMP Header: {'type': 8, 'code': 0, 'checksum': 27230, 'id': 64096, 'seq': 0}
[DEBUG] Sent ICMP Payload: b'A\xd7\x85\xf0p \x00\xfeQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Function Returned: send_one_ping -> None
[DEBUG] Function Called: receive_one_ping({'sock': <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1, laddr=('0.0.0.0', 1)>, 'icmp_id': 64096, 'seq': 0, 'timeout': 4})
[DEBUG] Received IP Header: {'version': 69, 'tos': 0, 'len': 76, 'id': 541, 'flags': 0, 'ttl': 112, 'protocol': 1, 'checksum': 17391, 'src_addr': 877577809, 'dest_addr': 167903236}
[DEBUG] Received ICMP Header: {'type': 0, 'code': 0, 'checksum': 31143, 'id': 37839, 'seq': 0}
[DEBUG] Received ICMP Payload: b'A\xd7\x85\xf0p$`BQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Uncatched ICMP Packet: {'type': 0, 'code': 0, 'checksum': 31143, 'id': 37839, 'seq': 0}
[DEBUG] Received IP Header: {'version': 69, 'tos': 0, 'len': 76, 'id': 22979, 'flags': 0, 'ttl': 112, 'protocol': 1, 'checksum': 50119, 'src_addr': 877653713, 'dest_addr': 167903236}
[DEBUG] Received ICMP Header: {'type': 0, 'code': 0, 'checksum': 10281, 'id': 46291, 'seq': 0}
[DEBUG] Received ICMP Payload: b'A\xd7\x85\xf0p%\x90\xbbQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Uncatched ICMP Packet: {'type': 0, 'code': 0, 'checksum': 10281, 'id': 46291, 'seq': 0}
[DEBUG] Received IP Header: {'version': 69, 'tos': 0, 'len': 76, 'id': 5346, 'flags': 0, 'ttl': 112, 'protocol': 1, 'checksum': 34106, 'src_addr': 262510314, 'dest_addr': 167903236}
[DEBUG] Received ICMP Header: {'type': 0, 'code': 0, 'checksum': 49435, 'id': 42067, 'seq': 0}
[DEBUG] Received ICMP Payload: b'A\xd7\x85\xf0p6\x088QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Uncatched ICMP Packet: {'type': 0, 'code': 0, 'checksum': 49435, 'id': 42067, 'seq': 0}
[DEBUG] Received IP Header: {'version': 69, 'tos': 0, 'len': 76, 'id': 30963, 'flags': 0, 'ttl': 112, 'protocol': 1, 'checksum': 15688, 'src_addr': 262503115, 'dest_addr': 167903236}
[DEBUG] Received ICMP Header: {'type': 0, 'code': 0, 'checksum': 52802, 'id': 58975, 'seq': 0}
[DEBUG] Received ICMP Payload: b'A\xd7\x85\xf0p8\xb9\x02QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Uncatched ICMP Packet: {'type': 0, 'code': 0, 'checksum': 52802, 'id': 58975, 'seq': 0}
[DEBUG] Received IP Header: {'version': 69, 'tos': 0, 'len': 76, 'id': 17565, 'flags': 0, 'ttl': 112, 'protocol': 1, 'checksum': 16051, 'src_addr': 917800615, 'dest_addr': 167903236}
[DEBUG] Received ICMP Header: {'type': 0, 'code': 0, 'checksum': 11540, 'id': 54747, 'seq': 0}
[DEBUG] Received ICMP Payload: b'A\xd7\x85\xf0pQj\x9cQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'`

**Comment by GoopyAspirin** [comment]
More Log in Centos7 :

PING google.co.kr (216.58.197.99) 56(84) bytes of data.
64 bytes from hkg12s01-in-f99.1e100.net (216.58.197.99): icmp_seq=1 ttl=48 time=36.0 ms
64 bytes from hkg12s01-in-f99.1e100.net (216.58.197.99): icmp_seq=2 ttl=48 time=35.9 ms
64 bytes from hkg12s01-in-f99.1e100.net (216.58.197.99): icmp_seq=3 ttl=48 time=35.7 ms
64 bytes from hkg12s01-in-f99.1e100.net (216.58.197.99): icmp_seq=4 ttl=48 time=35.8 ms
64 bytes from hkg12s01-in-f99.1e100.net (216.58.197.99): icmp_seq=5 ttl=48 time=35.7 ms
^C
--- google.co.kr ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4017ms
rtt min/avg/max/mdev = 35.705/35.859/36.013/0.244 ms



PING 52.79.186.81 (52.79.186.81) 56(84) bytes of data.
^C
--- 52.79.186.81 ping statistics ---
147 packets transmitted, 0 received, 100% packet loss, time 146009ms


### CentOS continues to wait when a timeout occurs. This seems to be causing the problem.

I think that's why different operating systems have different phenomena.

**Comment by GoopyAspirin** [comment]
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
[root@kang154123-84100 ~]# ping 52.79.186.81 -W 1
PING 52.79.186.81 (52.79.186.81) 56(84) bytes of data.
ç^C
--- 52.79.186.81 ping statistics ---
21 packets transmitted, 0 received, 100% packet loss, time 20002ms

[root@kang154123-84100 ~]# ping 52.79.186.81 -w 1
PING 52.79.186.81 (52.79.186.81) 56(84) bytes of data.

--- 52.79.186.81 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

[root@kang154123-84100 ~]# ping 52.79.186.81 -w 3
PING 52.79.186.81 (52.79.186.81) 56(84) bytes of data.

--- 52.79.186.81 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2001ms

###In centOS, you can specify the maximum time by setting -w [time (sec)] with the Ping option.

###I didn't know, so I tried the following via alias:

##But not improved.

[root@kang154123-84100 ~]# alias ping='ping -w 3 '
[root@kang154123-84100 ~]# ping 52.79.186.81
PING 52.79.186.81 (52.79.186.81) 56(84) bytes of data.

--- 52.79.186.81 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2001ms

**Comment by kyan001** [comment]
Hi all,

I think I just fixed this problem. This bug is not related to platform, and I finally reproduced it. This bug occurs when there are a lot of packets passed to your network interface in a short time and in the meantime the pinging destination address timeouts. 

Thanks a lot for your helps. Please try the new version (>= 2.4.4) and tell me if this bug is fixed.

**Comment by GoopyAspirin** [comment]
@kyan001 

Thank you. You have now verified that it works correctly in all environments.

But there were other complex issues.

Situation A) I use threads to ping multiple servers at the same time. (Sent to approximately 20 or more hosts)

In older versions that did not resolve the timeout problem, the ping was sent to all hosts reliably, even under situation A.

However, in the latest version, the following problems occur under the same situation.

Problem: Sending more than one ping at the same time or at the same time returns a value in Timeout. In fact, the target host receives a ping normally.

My execution environment: I keep pinging about 20 hosts.
Create one thread per host at a time. And that thread grows every 3 seconds, up to 20.

In the process, Ping returns Timeout.

I hope you can solve this problem.
Thank you.
